@startuml

class Registro {
   -usuario: Usuario
   -controlador: Controlador

   +Boolean sePuedeRegistrar()
}

class Usuario {
   -nombre: String
   -contrasenia: String
}

class Controlador {
    -longitudMaxima: Integer
    -longitudMinima: Integer
    -top10000PeoresContrasenias: File

    +Boolean esValida(String clave)
}

Registro o-- Usuario
Registro o-- Controlador

@enduml

