@startuml

class Registro {
   -usuario: Usuario
   -controlador: Controlador

   +Boolean sePuedeRegistrar()
}

class Usuario {
   -nombre: String
   -contrasenia: String
}

class Controlador {
    -longitudMaxima: Integer
    -longitudMinima: Integer
    -top10000PeoresContrasenias: File
    -regex: Regex

    +Boolean esValida(String clave)
}

class Regex {
    +Boolean cumpleRegex(String clave, Integer longitudMinima, Integer longitudMaxima)
}

Registro o-- Usuario
Registro o-- Controlador
Controlador o-- Regex

@enduml