
@startuml
'========================================== Clases de la entrega 1 ============================================='

class Heladera {
    -direccion: Direccion
    -nombre: String
    -capacidadMaximaViandas: Integer
    -List<Vianda> viandas
    -fechaCreacion: Date

    'TODO'
    -modeloHeladera: ModeloHeladera
    -ultimaTemperatura: Float
    -sensorMovimiento: SensorMovimiento

    +void agregarVianda (Vianda vianda)
    +boolean estaActiva ()
}

class Direccion {
    -ubicacion: String
    -longitud: Float
    -latitud: Float
    -provincia: Provincia
}

class Provincia {
    -nombreProvincia: String
    -ciudad: Ciudad
}

class Ciudad {
    -nombreCiudad: String
    -barrio: Barrio
}

class Barrio {
    -nombreBarrio: String
    -calle: String
    -numero: Integer
}

class Vianda {
    -comida: Comida
    -fechaDonacion: Date
    -colaborador: PersonaFisica
    -heladera: Heladera
    -calorias: Integer
    -peso: Integer
    -entregada: Boolean
}

class Comida {
    -nombre: String
    -vencimiento: Date
}

class Vulnerable {
    -nombre: String
    -fechaNacimiento: Date
    -fechaRegistro: Date
    -domicilio: Direccion
    -tipoDocumento: TipoDocumento
    -numeroDeDocumento: Integer
    -List<Vulnerable> menoresACargo
    -tarjeta: Tarjeta
}

class Colaborador{
    'De Persona Fisica'
    -nombre: String
    -apellido: String
    -medioContacto: String

    'De Persona Juridica'
    -razonSocial: String
    -tipo: String
    -rubro: String
    -direccion: Direccion

    -tipoColaborador: TipoColaborador
    -respuestaFormulario: RespuestaFormulario
    -reconocimiento: Reconocimiento
    -List<Colaboracion> colaboraciones

    +void realizarColaboracion (Colaboracion colaboracion)
}

enum TipoColaborador {
    FISICO,
    JURIDICO
}

class Formulario {
    -List<Pregunta> preguntas
}

class RespuestaFormulario {
    -nombre: String
    -descripcion: String
    -List<Respuesta> respuestas
    -formulario: Formulario
}

class Pregunta {
    -pregunta: String
    -esOpcional: Boolean
    -Set<Opcion> opciones
    -tipoDeSuRespuesta: TipoPregunta
}

class Respuesta {
    -pregunta: Pregunta
    -respuestaTextoLibre: String
    -Set<Opcion> respuestaMultipleChoice
    -respuestaSingleChoice: Opcion
    -tipoRespuesta: TipoPregunta
}

class Opcion {
    -opcion: String
}

enum TipoPregunta {
    MULTIPLE_CHOICE,
    SINGLE_CHOICE,
    TEXTO_LIBRE
}

class Colaboracion {
    -fechaDonacion: Date
    -monto: Integer
    -frecuencia: String
    -List<Vianda> viandas
    -heladeraOrigen: Heladera
    -heladeraDestino: Heladera
    -cantViandas: Integer
    -motivoDistribucion: String
    -fechaDistribucion: Date
    -cantTarjetas: Integer
    -tipoColaboracion: TipoColaboracion
}

enum TipoColaboracion {
    DONAR_DINERO,
    DONAR_VIANDA,
    DISTRIBUIR_VIANDA,
    COLOCAR_HELADERA,
    DISTRIBUIR_TARJETAS
}

'========================================== Clases de la entrega 2 ============================================='

class ModeloHeladera {
    -temperaturaMinima: Float
    -temperaturaMaxima: Float
}

class SensorMovimiento {
    -ubicacionActual: Direccion

    +void alertarAlSistema()
}

'TODO'
class Reconocimiento {
    -puntosActuales: Float
    -puntosUsados: Float
    -formulaCalculoDePuntos: Formula

    +Float calcularPuntos ()
}

class Formula {
    +Float calcular(Reconocimiento unReconocimiento)
}

class Tarjeta {
    -codigo: String
    -cantidadDeUsos: Integer
    -Set<RegistroUso> registroUsos
    -informacionRegistro: InformacionRegistro

    +void actualizarCantidadUsos(Vulnerable unVulnerable)
}

class RegistroUso {
    -fechaUtilizacion: Date
    -heladera: Heladera
}

class InformacionRegistro {
    -colaborador: PersonaFisica
    -vulnerable: Vulnerable
}

class Tecnico {
    -nombre: String
    -apellido: String
    -tipoDocumento: TipoDocumento
    -numeroDeDocumento: Integer
    -cuil: Integer
    -medioContacto: String
    -areaDeCobertura: Provincia
}

enum TipoDocumento {
    DNI,
    LIBRETA_ENROLAMIENTO,
    PASAPORTE
}

'TODO'
class EmpresaAsociada {
    -List<Oferta> ofertas
}

class Oferta {
    -nombre: String
    -puntosNecesarios: Float
    -imagenIlustrativa: Image
}

'================================================== Relaciones ================================================'

Heladera o--"*" Vianda
Vianda --> Heladera
Colaboracion --> TipoColaboracion
Colaborador -->"*" Colaboracion
Colaboracion --->"*" Vianda
Colaboracion -> Heladera
Vulnerable ->"*" Vulnerable
Heladera o-- Direccion
Colaborador o--- Direccion
Vianda o-- Comida
Vianda o- Colaborador
Formulario o--"*" Pregunta
RespuestaFormulario o--"*" Respuesta
RespuestaFormulario o-- Formulario
Colaborador o--- RespuestaFormulario
Respuesta -->"*" Opcion
Respuesta o-- Pregunta
Pregunta ->"*" Opcion
Pregunta *--> TipoPregunta
Respuesta o-- TipoPregunta
Direccion --> Provincia
Provincia --> Ciudad
Ciudad --> Barrio
Vulnerable o-- Direccion
Vulnerable o-- TipoDocumento
Tecnico o-- TipoDocumento
Vulnerable o-- Tarjeta
Tarjeta o--"*" RegistroUso
Tarjeta *-- InformacionRegistro
InformacionRegistro o-- Colaborador
InformacionRegistro o-- Vulnerable
Reconocimiento o-- Formula
Formula ..> Reconocimiento
SensorMovimiento o-- Direccion
EmpresaAsociada o--"*" Oferta
Heladera --> ModeloHeladera
Colaborador *--- TipoColaborador

@enduml