@startuml

class Heladera {
    -direccion: Direccion
    -nombre: String
    -capacidadMaximaViandas: Integer
    -viandas: List<Vianda>
    -fechaCreacion: Date

    +void agregarVianda (Vianda vianda)
}

'TODO''revisar la parte de ubicacion'
class Direccion {
    'habria q ver si esta bien lo de ubicacion'
    -ubicacion: String
    -longitud: Float
    -latitud: Float
    -provincia: Provincia

    '+ detalleDireccion: String'
}

class Provincia {
    -nombreProvincia: String
    -ciudad: Ciudad
}

class Ciudad {
    -nombreCiudad: String
    -barrio: Barrio
}

class Barrio {
    -nombreBarrio: String
    -calle: String
    -numero: Integer
    '-infoExtra: String tipo primer piso/casa/segundo a'
}

class Vianda {
    -comida: Comida
    -fechaDonacion: Date
    -colaborador: PersonaFisica
    -heladera: Heladera
    -calorias: Integer
    -peso: Integer
    -entregada: Boolean
}

class Comida {
    -nombre: String
    -vencimiento: Date
}

class Vulnerable {
    -nombre: String
    -fechaNacimiento: Date
    -fechaRegistro: Date
    -tieneDomicilio: Boolean
    -domicilio: String
    -tieneDNI: Boolean
    -dni: String
    -menoresACargo: List<Vulnerable>
}

class PersonaFisica {
    -nombre: String
    -apellido: String
    -medioContacto: String
    -formulario: Formulario
    -List<Colaboracion> colaboraciones

    +void realizarColaboracion (Colaboracion colaboracion)
}

class PersonaJuridica {
    -razonSocial: String
    -tipo: String
    -rubro: String
    -medioContacto: String
    -direccion: Direccion
    -formulario: Formulario
    -List<Colaboracion> colaboraciones

    +void realizarColaboracion (Colaboracion colaboracion)
}

class Colaboracion {
    -fechaDonacion: Date
    -monto: Integer
    -frecuencia: String
    -List<Vianda> viandas
    -heladeraOrigen: Heladera
    -heladeraDestino: Heladera
    -cantViandas: Integer
    -motivoDistribucion: String
    -fechaDistribucion: Date
    -tipoColaboracion: TipoColaboracion
}

class Formulario {
    List<Pregunta> preguntas
    respuestaFormulario: RespuestaFormulario

    +Respuesta respuestaAPregunta (Pregunta pregunta)
}

class RespuestaFormulario {
    List<Respuesta> respuestas

    +void responderPregunta (Respuesta respuesta)
}

class Pregunta {
    pregunta: String
}

class Respuesta {
    respuesta: String
}

enum TipoColaboracion {
    DONAR_DINERO,
    DONAR_VIANDA,
    DISTRIBUIR_VIANDA,
    COLOCAR_HELADERA
}

Heladera o-"*" Vianda
Vianda -> Heladera
Colaboracion -> TipoColaboracion
PersonaFisica ->"*" Colaboracion
PersonaJuridica ->"*" Colaboracion
Colaboracion ->"*" Vianda
Colaboracion -> Heladera
Vulnerable ->"*" Vulnerable
Heladera o-- Direccion
PersonaJuridica o-- Direccion
Vianda o-- Comida
Vianda o-- PersonaFisica
Formulario o--"*" Pregunta
Formulario *-- RespuestaFormulario
RespuestaFormulario o--"*" Respuesta
PersonaFisica o-- Formulario
PersonaJuridica o-- Formulario
Direccion -> Provincia
Provincia -> Ciudad
Ciudad -> Barrio

@enduml