@startuml

left to right direction
actor :personaFisica: as fisica
actor :personaJuridica: as juridica
actor :ONG: as ong

rectangle DominioPrincipal {
    usecase "Registrarse" as UC0

    usecase "Completar formulario" as UC1

    usecase "Dar alta colaborador" as UC2
    usecase "Dar baja colaborador" as UC3
    usecase "Modificar colaborador" as UC4

    usecase "Dar alta vulnerable" as UC5

    usecase "Dar alta heladera" as UC6
    usecase "Dar baja heladera" as UC7
    usecase "Modificar heladera" as UC8

    usecase "Donar vianda" as UC9
    usecase "Donar dinero" as UC10
    usecase "Colocar heladera" as UC11
    usecase "Distribuir viandas" as UC12

    usecase "Visualizar mapa de heladeras" as UC13
}

fisica --> UC0
juridica --> UC0

fisica --> UC9
fisica --> UC10
fisica --> UC12

juridica --> UC10
juridica --> UC11

ong --> UC2
ong --> UC3
ong --> UC4
ong --> UC5
ong --> UC6
ong --> UC7
ong --> UC8

fisica --> UC13
juridica --> UC13
ong --> UC13

UC9 ..> UC1 : <<includes>>
UC10 ..> UC1 : <<includes>>
UC11 ..> UC1 : <<includes>>
UC12 ..> UC1 : <<includes>>
UC1 ..> UC0 : <<includes>>

@enduml