@startuml

class Heladera {
    -longitud: Float
    -latitud: Float
    -direccion: String
    -nombre: String
    -capacidadMaximaViandas: Integer
    -List<Vianda> viandas
    -fechaCreacion: Date

    +void agregarVianda(Vianda vianda)
}

class Vianda {
    -comida: String
    -vencimiento: Date
    -fechaDonacion: Date
    -colaborador: String
    -heladera: Heladera
    -calorias: Integer
    -peso: Integer
    -entregada: Boolean
}

class Vulnerable {
    -nombre: String
    -fechaNacimiento: Date
    -fechaRegistro: Date
    -tieneDomicilio: Boolean
    -domicilio: String
    -tieneDNI: Boolean
    -dni: String
    -tieneMenoresACargo: Boolean
    -cantMenoresACargo: Integer
}

class PersonaFisica {
    -nombre: String
    -apellido: String
    -fechaNacimiento: Date
    -medioContacto: String
    -direccion: String
    -List<Colaboracion> colaboraciones

    +void realizarColaboracion(Colaboracion colaboracion)
}

class PersonaJuridica {
    -razonSocial: String
    -tipo: String
    -rubro: String
    -medioContacto: String
    -direccion: String
    -List<Colaboracion> colaboraciones

    +void realizarColaboracion(Colaboracion colaboracion)
}

class Colaboracion {
    -fechaDonacion: Date
    -monto: Integer
    -frecuencia: String
    -List<Vianda> viandas
    -heladeraOrigen: Heladera
    -heladeraDestino: Heladera
    -cantViandas: Integer
    -motivoDistribucion: String
    -fechaDistribucion: Date
    -tipoColaboracion: TipoColaboracion
}

enum TipoColaboracion {
    DONAR_DINERO,
    DONAR_VIANDA,
    DISTRIBUIR_VIANDA,
    COLOCAR_HELADERA
}

Heladera o-"*" Vianda
Vianda -> Heladera
Colaboracion -> TipoColaboracion
PersonaFisica ->"*" Colaboracion
PersonaJuridica ->"*" Colaboracion
Colaboracion ->"*" Vianda
Colaboracion -> Heladera

@enduml